#version 450

layout (binding = 0, rgba8) uniform writeonly image2D outImage;
layout(std140, binding = 1) readonly buffer MyBuffer{
    int data[];
} ssbo;
layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

void main() 
{
    uint index = gl_GlobalInvocationID.x;
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    uint bIndex = gl_LocalInvocationID.x;
    vec4 color = vec4(
        ssbo.data[bIndex],
        float(pixel.y) / 16.0,
        0.0,
        1.0
    );

    imageStore(outImage, pixel, color);
}